services:
  yeti-fargate-basic:
    image: 360509112437.dkr.ecr.us-east-1.amazonaws.com/yeti-fargate-basic:latest
    container_name: yeti-fargate-basic
    env_file:
      - .env
    ports:
      - 80:80
    restart: unless-stopped

